repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.2.0
  hooks:
  - id: trailing-whitespace
    exclude: >
      (?x)^(
        ^compiler/test/runnable/extra-files/.*$|
        ^compiler/test/compilable/extra-files/.*$|
      )$
  - id: end-of-file-fixer
    exclude: >
      (?x)^(
        ^compiler/test/runnable/extra-files/.*$|
        ^compiler/test/compilable/extra-files/.*$|
      )$
  - id: check-merge-conflict
  - id: check-added-large-files
  - id: detect-private-key
  - id: no-commit-to-branch
    args: [--branch, master]
- repo: https://github.com/sirosen/check-jsonschema
  rev: 0.15.1
  hooks:
    - id: check-github-workflows
