language: d
d:
  - dmd
  - gdc
  - ldc

script: ./travis.sh

sudo: false
addons:
  apt:
    packages:
    - g++-multilib
    - gdb
    - libcurl3-gnutls:i386

env:
  - MODEL=32
  - MODEL=64

matrix:
  include:
    - os: osx
      d: dmd
      env: MODEL=32
    - os: osx
      d: dmd
      env: MODEL=64
  exclude:
    # gdc doesn't neither comes w/ multilib support nor picks up system-wide -lstdc++ lgcc_s
    - d: gdc
      env: MODEL=32
