# Learn more: https://aka.ms/yaml
variables:
  HOST_DMD_VERSION: 2.084.1

jobs:
  - job: Windows
    timeoutInMinutes: 120
    pool:
      vmImage: 'vs2017-win2016'
    variables:
      VSINSTALLDIR: C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\
    strategy:
      matrix:
        x64:
          OS: Win_64
          MODEL: 64
          ARCH: x64
          D_COMPILER: dmd
        #x86:
          #OS: Win_32
          #MODEL: 32
          #ARCH: x86
          #D_COMPILER: dmd
    steps:
      - template: .azure-pipelines/windows.yml
  - job: Windows_VisualD
    timeoutInMinutes: 120
    pool:
      vmImage: 'vs2017-win2016'
    variables:
      VSINSTALLDIR: C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\
    strategy:
      matrix:
        visuald-ldc:
          OS: Win_32
          MODEL: 32
          ARCH: x86
          D_COMPILER: ldc
          VISUALD_VER: v0.49.0
          LDC_VERSION: 1.14.0
    steps:
      - template: .azure-pipelines/windows-visual-studio.yml
