# Learn more: https://aka.ms/yaml
variables:
  VSINSTALLDIR: C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\

jobs:
  - job: Windows_DMD_bootstrap
    timeoutInMinutes: 60
    pool:
      vmImage: 'vs2017-win2016'
    variables:
      D_COMPILER: dmd
      HOST_DMD_VERSION: 2.079.0
    strategy:
      matrix:
        x64:
          OS: Win_64
          MODEL: 64
          ARCH: x64
        x86-OMF:
          OS: Win_32
          MODEL: 32
          ARCH: x86
    steps:
      - template: .azure-pipelines/windows.yml

  - job: Windows_DMD_latest
    timeoutInMinutes: 60
    pool:
      vmImage: 'vs2017-win2016'
    variables:
      D_COMPILER: dmd
      HOST_DMD_VERSION: LATEST
    strategy:
      matrix:
        x64:
          OS: Win_64
          MODEL: 64
          ARCH: x64
        x86-OMF:
          OS: Win_32
          MODEL: 32
          ARCH: x86
    steps:
      - template: .azure-pipelines/windows.yml
      - template: .azure-pipelines/windows-artifact.yml

  - job: Windows_Coverage
    timeoutInMinutes: 60
    pool:
      vmImage: 'vs2017-win2016'
    variables:
      D_COMPILER: dmd
      HOST_DMD_VERSION: LATEST
      DMD_TEST_COVERAGE: 1
    strategy:
      matrix:
        x64:
          OS: Win_64
          MODEL: 64
          ARCH: x64

        # x64 only because 32bit causes weird linker errors for several tests???
        # x86-OMF:
        #   OS: Win_32
        #   MODEL: 32
        #   ARCH: x86
    steps:
      - template: .azure-pipelines/windows.yml

  - job: Windows_VisualD_LDC
    timeoutInMinutes: 60
    pool:
      vmImage: 'vs2017-win2016'
    variables:
      D_COMPILER: ldc
      VISUALD_VER: v0.49.0
      LDC_VERSION: 1.23.0
    strategy:
      matrix:
        x64_Debug:
          OS: Win_64
          MODEL: 64
          ARCH: x64
          CONFIGURATION: Debug
        x86-mscoff:
          OS: Win_32
          MODEL: 32mscoff
          ARCH: x86
        x86-mscoff_MinGW:
          OS: Win_32
          MODEL: 32mscoff
          ARCH: x86
          C_RUNTIME: mingw
    steps:
      - template: .azure-pipelines/windows-visual-studio.yml
